//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AV.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AV.Common.ResourceStore", typeof(ResourceStore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation Completed.
        /// </summary>
        internal static string CompleteValuationEmailBody_Issuer {
            get {
                return ResourceManager.GetString("CompleteValuationEmailBody_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;document-background&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Detailed Valuation Report&lt;/title&gt;
        ///		
        ///&lt;link href=&quot;https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; integrity=&quot;sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///#main{
        ///	height:fit-content;
        ///}
        ///
        ///    .container-card {
        ///        position: relative;
        ///        margin: 0px auto;
        ///        max-width: 790px;
        ///        padding:15px;
        ///        backgroun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailedValuationReport {
            get {
                return ResourceManager.GetString("DetailedValuationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gosmartvalue {
            get {
                object obj = ResourceManager.GetObject("gosmartvalue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionAccepted_Corporate {
            get {
                return ResourceManager.GetString("InstructionAccepted_Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionBookingConfirmed_Corporate {
            get {
                return ResourceManager.GetString("InstructionBookingConfirmed_Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionNew_CorporateUser {
            get {
                return ResourceManager.GetString("InstructionNew_CorporateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionNew_Valuer {
            get {
                return ResourceManager.GetString("InstructionNew_Valuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionRejected_Issuer {
            get {
                return ResourceManager.GetString("InstructionRejected_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAccount_Confirmation {
            get {
                return ResourceManager.GetString("UserAccount-Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAccount_PasswordReset {
            get {
                return ResourceManager.GetString("UserAccount-PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin: 0 auto; max-width: 600px; background: #ffffff&quot;&gt;
        ///    &lt;table role=&quot;presentation&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-size: 0px; width: 100%; background: #ffffff; border-top: 3px solid #fead0d&quot; align=&quot;center&quot; border=&quot;0&quot;&gt;
        ///        &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center; vertical-align: top; font-size: 0px; padding: 40px 30px 30px 30px&quot;&gt;
        ///
        ///                &lt;div aria-labelledby=&quot;mj-column-per-100&quot; class=&quot;m_-8535416616635464349mj-column-per-100&quot; style=&quot;vertical-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValuationAccepted_Client {
            get {
                return ResourceManager.GetString("ValuationAccepted_Client", resourceCulture);
            }
        }
    }
}
