SELECT * FROM gosmartvalue.Locations;

INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	110,7,'Chimochima');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	54,4,'Matebele');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	55,3,'Kopong');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	56,3,'Matseta');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	57,4,'Mokatse');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	58,4,'Modipane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	59,4,'Tloaneng');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	60,4,'Artesia');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	61,9,'Karakubisi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	62,9,'Gakutlo');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	63,4,'Morwa');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	64,2,'Ranaka');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	65,2,'Mookolodi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	66,3,'Kgope');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	67,3,'Mmanoko');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	68,2,'Pitsane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	69,1,'Mathethe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	70,1,'Lotlhakane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	71,3,'Gamodubo');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	72,1,'Sese');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	73,4,'Leshibetse');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	74,4,'Pilane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	75,4,'Malotwane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	76,4,'Kgomodiatshaba');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	77,3,'Ditshekwane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	78,2,'Mmashia');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	79,2,'Diphiring');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	80,1,'Digagwana');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	81,2,'South East');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	82,2,'Kgatleng');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	83,2,'Kweneng');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	84,2,'Lorolwane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	85,2,'Tswaneng');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	86,2,'Molapowabojang');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	87,10,'Lokgwabe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	88,2,'Kanngwe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	89,6,'Selebi Phikwe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	90,7,'Maun');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	91,8,'Kasane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	92,8,'Kazungula');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	93,7,'Shakawe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	94,5,'Central District');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	95,6,'Tati Siding');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	96,5,'Mathangwane');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	97,7,'Samedupi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	98,5,'Bobonong');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	99,7,'Gumare');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	100,6,'North East');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	101,5,'Mopipi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	102,7,'HainaVeld');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	103,8,'Muchenje');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	104,7,'Xobe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	105,5,'Moinyabana');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	106,5,'Metsimaswaana');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	107,8,'Chobe District');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	108,5,'Mogapinyana');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	109,5,'Makoro');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	110,5,'Rakops');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	111,7,'Chimochima');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	112,6,'Sowa');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	113,5,'Pilikwe');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	114,5,'Tuli Block');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	115,7,'Chanoga');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	116,6,'Dukwi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	117,5,'Kalamare');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	118,6,'Borolong');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	119,5,'Kaka');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	120,7,'Makalamabedi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	121,7,'Xudum');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	122,5,'Motloutse');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	123,7,'Matlapana');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	124,8,'Lesoma');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	125,5,'Shashe Mooke');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	126,7,'Matlapeng');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	127,5,'Matshelagamapedi');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	128,8,'Phandamatenga');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	129,5,'Mosu');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	130,7,'Sexaxa');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	131,5,'Lecheng');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	132,7,'Eretsha');
INSERT INTO `gosmartvalue`.`Locations` (`Id`,`DistrictId`, `Name`) VALUES (	133,5,'Topisi');